// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as AddUserForm$ReactHooksTemplate from "../components/AddUserForm.bs.js";
import * as PageHeading$ReactHooksTemplate from "../components/PageHeading.bs.js";

function AddUser(Props) {
  return React.createElement(React.Fragment, {
              children: null
            }, React.createElement(PageHeading$ReactHooksTemplate.make, {
                  text: "Add User"
                }), React.createElement(AddUserForm$ReactHooksTemplate.make, { }));
}

var make = AddUser;

export {
  make ,
  
}
/* react Not a pure module */
