// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Reactstrap from "reactstrap";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

function Navigation(Props) {
  return React.createElement(React.Fragment, {
              children: React.createElement(Reactstrap.Navbar, {
                    light: true,
                    color: "light",
                    expand: "md",
                    children: null
                  }, React.createElement(Reactstrap.NavbarBrand, {
                        children: "Reason Form Example "
                      }), React.createElement(Reactstrap.Nav, {
                        vertical: false,
                        children: null
                      }, React.createElement(Reactstrap.NavItem, {
                            children: React.createElement(Reactstrap.Button, {
                                  color: "link",
                                  onClick: (function (param) {
                                      return ReasonReactRouter.push("/addUser");
                                    }),
                                  children: "Add User"
                                })
                          }), React.createElement(Reactstrap.NavItem, {
                            children: React.createElement(Reactstrap.Button, {
                                  color: "link",
                                  onClick: (function (param) {
                                      return ReasonReactRouter.push("/listUsers");
                                    }),
                                  children: "List Users"
                                })
                          })))
            });
}

var make = Navigation;

export {
  make ,
  
}
/* react Not a pure module */
