// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";

function PageHeading(Props) {
  var text = Props.text;
  return React.createElement(React.Fragment, {
              children: React.createElement("h4", {
                    style: {
                      paddingTop: "1em",
                      paddingBottom: "1em"
                    }
                  }, text)
            });
}

var make = PageHeading;

export {
  make ,
  
}
/* react Not a pure module */
