// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as React from "react";
import * as Reactstrap from "reactstrap";

function s(prim) {
  return prim;
}

function UserList(Props) {
  var userState = Props.userState;
  var tmp;
  if (typeof userState === "number") {
    switch (userState) {
      case 0 : 
          tmp = React.createElement("tr", undefined, React.createElement("td", {
                    colSpan: 4
                  }, "Error while loading data."));
          break;
      case 1 : 
          tmp = React.createElement("tr", undefined, React.createElement("td", {
                    colSpan: 4
                  }, "Database ho no users yet."));
          break;
      case 2 : 
          tmp = React.createElement("tr", undefined, React.createElement("td", {
                    colSpan: 4
                  }, "Loading Data..."));
          break;
      
    }
  } else {
    tmp = $$Array.of_list(List.mapi((function (i, user) {
                return React.createElement("tr", {
                            key: user[/* id */0]
                          }, React.createElement("td", undefined, String(i + 1 | 0)), React.createElement("td", undefined, user[/* email */1]), React.createElement("td", undefined, user[/* firstName */2]), React.createElement("td", undefined, user[/* lastName */3]));
              }), userState[0]));
  }
  return React.createElement(React.Fragment, {
              children: React.createElement(Reactstrap.Table, {
                    children: null
                  }, React.createElement("thead", undefined, React.createElement("tr", undefined, React.createElement("th", undefined, "#"), React.createElement("th", undefined, "Email"), React.createElement("th", undefined, "First Name"), React.createElement("th", undefined, "Last Name"))), React.createElement("tbody", undefined, tmp))
            });
}

var make = UserList;

export {
  s ,
  make ,
  
}
/* react Not a pure module */
