// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Reactstrap from "reactstrap";
import * as Router$ReactHooksTemplate from "./Router.bs.js";
import * as Navigation$ReactHooksTemplate from "./components/Navigation.bs.js";

function App(Props) {
  return React.createElement(Reactstrap.Container, {
              children: null
            }, React.createElement(Navigation$ReactHooksTemplate.make, { }), React.createElement(Router$ReactHooksTemplate.make, { }));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
