// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";
import * as AddUser$ReactHooksTemplate from "./routes/AddUser.bs.js";
import * as ListUsers$ReactHooksTemplate from "./routes/ListUsers.bs.js";

function Router(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url[/* path */0];
  var exit = 0;
  if (match) {
    switch (match[0]) {
      case "addUser" : 
          if (match[1]) {
            exit = 1;
          } else {
            return React.createElement(AddUser$ReactHooksTemplate.make, { });
          }
          break;
      case "listUsers" : 
          if (match[1]) {
            exit = 1;
          } else {
            return React.createElement(ListUsers$ReactHooksTemplate.make, { });
          }
          break;
      default:
        exit = 1;
    }
  } else {
    return React.createElement(ListUsers$ReactHooksTemplate.make, { });
  }
  if (exit === 1) {
    return React.createElement("div", undefined, "Sorry, page not found");
  }
  
}

var make = Router;

export {
  make ,
  
}
/* react Not a pure module */
